39 kho zadania powtórzeniowe podstawy programowania 2
KarolinaStangel/python-practice pull request #43
Opened 2020-03-22 21:15 UTC by Slavencjusz

Proszę o sprawdzenie. Zadanie 2 może mieć jakieś błędy.

2020-03-22 21:26 UTC, KarolinaStangel requested changes

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +    num = input(text)
Tak jak napisałam Rafałowi, dałabym tutaj pełną nazwę. SHIFT + F6 or sth

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +    print("Brak rozwiązania.")
Technicznie to nie brak rozwiązania tylko:
- brak rozwiązania, gdy b != 0
- nieskończenie wiele rozwiązań, gdy b == 0

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +    print("x = " + str(rozw))
Tu też możnaby zaokrąglić wynik na wszelki wypadek.

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +# 1
Przy wysyłaniu do wykładowcy zrobiłabym jednak trzy oddzielne pliki

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +    print("To nie jest równanie kradratowe.")
kradratowe

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +    rozw_1 = round((-b-math.sqrt(delta))/(2*a), 2)
dałabym odstępy między "b - math", etc

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +    rozw_2 = round((-b+math.sqrt(delta))/(2*a), 2)
te nazwy mi się średnio podobają rozw_2

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +def get_side(text):
W sumie tutaj należałoby jeszcze zabezpieczyć się przed otrzymaniem liczby ujemnej.

2020-03-22 21:26 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +        triangle_area = P = round(math.sqrt(p * (p - a) * (p - b) * (p - c)), 2)
Wow... a mówili, że pajton-srajton.... Co to za cuda, żę triangle_area = P = cośtam?

2020-03-23 17:25 UTC, Wodianoj approved these changes
Według mnie jest dobrze.

2020-03-23 18:02 UTC, KarolinaStangel approved these changes

2020-03-23 18:02 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +    number = input(text)
Wydaje mi się, że można to jeszcze skrócić:

```
    while True:
        try:
            number = float(number)
            return number
        except:
            number = input("Błędna wartość. Spróbuj ponownie:\n")
```

2020-03-23 18:02 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/39_Kho_Zad_powt_PodstProg2.py
> +        try:
Tu podobnie

2020-03-23 18:02 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/Mazurek_Sławomir_Podstawy_programowania_2_Zadanie_powtórzenie_3.py
> +    while True:
Chyba da się to jescze bardziej skompresować:

```
   while True:
        try:
            number = float(number)
            return number
        except:
            number = input("Błędna wartość. Spróbuj ponownie:\n")
    
```
Break oznacza wyjśie z pętli.
Return wychodzi z funkcji (i zwraca najczęściej jakąś wartość).
Zamiast dawać breaka, wychodzić z pętli a potem zwracać wartość, możemy skrócić to o jeden etap i od razu wyjsć z funkcji zwracając zwalidowaną liczbę.

2020-03-23 18:02 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/Mazurek_Sławomir_Podstawy_programowania_2_Zadanie_powtórzenie_2.py
> +            break
Tak jak w innych miejscach

2020-03-23 18:02 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/Mazurek_Sławomir_Podstawy_programowania_2_Zadanie_powtórzenie_3.py
> +            break
należałoby również sprawdzić, czy bok trójkąta nie jest przypadkiem mniejszy lub równy zero i w takim przypakdu poinfrmować użytkownika o błędzie i poprosić go o input, a w przeciwnym wypadku - wyjść z pętli z końcową wartością

2020-03-23 18:02 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/Mazurek_Sławomir_Podstawy_programowania_2_Zadanie_powtórzenie_2.py
> +else:
No dobrze, a co z przypadkiem, że delta jest RÓWNA zero?

2020-03-23 18:02 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/Mazurek_Sławomir_Podstawy_programowania_2_Zadanie_powtórzenie_1.py
> +    solution = round((-b / a), 2)
dałąbym raczej result

2020-03-23 18:16 UTC, KarolinaStangel commented on Podstawy programowania/Ćwiczenia powtórzeniowe/Mazurek_Sławomir_Podstawy_programowania_2_Zadanie_powtórzenie_3.py
> +            break
```
def get_side():
    length = input()
    while True:
        try:
            length = float(length)
            if length <= 0:
                length = input("Długość boku nie może być mniejsza lub równa zero. Spróbuj jeszcze raz.\n")
            else:
                return length
        except:
            length = input("Nieprawidłowa wartość. Spróbuj jeszcze raz.\n")
```

2020-04-14 19:52 UTC, merged